#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 20 15:01:12 2022

@author: dharmendrakhakhar
"""

# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Z0WBv4VAZO0GUqJIHGghWPwH9INg9HS
"""

import numpy as np

class board:
    def __init__ (self, size = (6,6), blocks = np.array([[4,4,4,3,2,1],[2,3,4,4,4,4]]), start = [2,2],
                  end = [5,5]):

        board = np.zeros(size)
        board[tuple(blocks)]=-1
        board[tuple(start)]=1
        board[tuple(end)]=-2
        self.endLoc = np.array(end)
        
        self.board = board
        self.currLoc = start



